#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-grizzled-slf4j_2.12
Version  : 1.3.4
Release  : 1
URL      : https://github.com/bmc/grizzled-slf4j/archive/release-1.3.4.tar.gz
Source0  : https://github.com/bmc/grizzled-slf4j/archive/release-1.3.4.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/clapper/grizzled-slf4j_2.12/1.3.2/grizzled-slf4j_2.12-1.3.2.jar
Source2  : https://repo.maven.apache.org/maven2/org/clapper/grizzled-slf4j_2.12/1.3.2/grizzled-slf4j_2.12-1.3.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-grizzled-slf4j_2.12-data = %{version}-%{release}
Requires: mvn-grizzled-slf4j_2.12-license = %{version}-%{release}

%description
# Grizzled-SLF4J: A simple, Scala-friendly front-end to SLF4J
[![Build Status](https://travis-ci.org/bmc/grizzled-slf4j.svg?branch=master)](https://travis-ci.org/bmc/grizzled-slf4j)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/org.clapper/grizzled-slf4j_2.11/badge.svg)](https://maven-badges.herokuapp.com/maven-central/org.clapper/grizzled-slf4j_2.11)

%package data
Summary: data components for the mvn-grizzled-slf4j_2.12 package.
Group: Data

%description data
data components for the mvn-grizzled-slf4j_2.12 package.


%package license
Summary: license components for the mvn-grizzled-slf4j_2.12 package.
Group: Default

%description license
license components for the mvn-grizzled-slf4j_2.12 package.


%prep
%setup -q -n grizzled-slf4j-release-1.3.4

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-grizzled-slf4j_2.12
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-grizzled-slf4j_2.12/LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-slf4j_2.12/1.3.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-slf4j_2.12/1.3.2/grizzled-slf4j_2.12-1.3.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-slf4j_2.12/1.3.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-slf4j_2.12/1.3.2/grizzled-slf4j_2.12-1.3.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/clapper/grizzled-slf4j_2.12/1.3.2/grizzled-slf4j_2.12-1.3.2.jar
/usr/share/java/.m2/repository/org/clapper/grizzled-slf4j_2.12/1.3.2/grizzled-slf4j_2.12-1.3.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-grizzled-slf4j_2.12/LICENSE.md
